# Logging levels
logging.level.org.springframework.security=TRACE
logging.level.org.springframework.security.oauth2=TRACE
logging.level.org.springframework.web=TRACE

# RSA key locations
rsa.public-key=classpath:certs/public.pem
rsa.private-key=classpath:certs/private.pem

# Server Port
server.port=8080
